### ISSUE TITLE
implement functions in the frontend.

### ISSUE THREAD

**Issue by bayanka99** [Expense-Tracker-BA/Expense-Tracker#17]
- [x] implement filter by date.
- [x] implement filter by cost.
- [x] implement filter by category.
- [x] implement filter by description.
- [x] implement insert expense in frontend.
- [x] implement remove expense in frontend.
- [x] implement update expense in forntend.

**Comment by bayanka99** [comment]
implemented filter by description and insert new expense

**Comment by bayanka99** [comment]
implemented done and update expense.

**Comment by Amihai-bl13** [comment]
Implemented Filter by date.
Still have left to do: Filter by cost & Filter by category (implement in the frontend & update the backend accordingly, with the cached list etc...). 
Will continue tomorrow.

**Comment by Amihai-bl13** [comment]
Implemented filter by cost & by category.
